version: "3"

networks:
  custom-network:
    driver: bridge

services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '8000:80'
    networks:
      - custom-network
  db:
    image: mysql
    command: --authentication_policy=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: reports
    expose:
      - '3306'
    ports:
      - '3306:3306'